name: Ask CodeGPT for feedback

on:
  pull_request:
    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created]

jobs:
  process-events:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Run CodeGPT
      if: github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, 'CodeGPT') && !contains(github.event.comment.body,'The following is a message from CodeGPT:'))
      uses: isat/codegpt@v1.0.0
      with:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        assistant_id: 'asst_5GJDXEpXsiOKxJF2wObNvuWX'
